# generated by configure / remove this line to disable regeneration
prefix="/home/blake/Research/quantum/artifact-new/qrane/lib/barvinok"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/blake/Research/quantum/artifact-new/qrane/barvinok-0.41.4/isl/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/home/blake/Research/quantum/artifact-new/qrane/barvinok-0.41.4/isl/./include"
package="isl"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "isl"
;; --help) pkg-config --help ; echo Buildscript Of "isl Library"
;; --modversion|--version) echo "0.23"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-lisl -lgmp"
       :
;; --cflags) echo -I${includedir} ""
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
