# generated by configure / remove this line to disable regeneration
prefix="/home/blake/Research/quantum/artifact-new/qrane/lib/barvinok"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/blake/Research/quantum/artifact-new/qrane/barvinok-0.41.4/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/home/blake/Research/quantum/artifact-new/qrane/barvinok-0.41.4/."
package="barvinok"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "barvinok"
;; --help) pkg-config --help ; echo Buildscript Of "barvinok Library"
;; --modversion|--version) echo "0.41.4"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-lbarvinok -lpolylibgmp -lisl -lntl -lgmp"
       :
;; --cflags) echo -I${includedir} "-I/home/blake/Research/quantum/artifact-new/qrane/lib/barvinok/include"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
